meta:
  exp_description: DiT ATTN vanilla
  exp_type: DiT_ATTN  
  device: cuda:5
  model_type: DiT_ATTN
  vae_latent: True
  mix: False

dependencies:
  dataset_path: data/paired_Mimic_vae_multi_nomic.pt
  checkpoints_dir: checkpoints
  vae_path: checkpoints/vae_model.pth
  ibe_path: checkpoints/ibe_model.pth

hyper_para:
  epochs: 30
  lr: 1.0e-4
  batch_size: 256
  ddpm:
    num_train_steps: 1000
    beta_start: 0.00085 
    beta_end: 0.0120
  DiT:
    hidden_size: 256
    depth: 7
    num_heads: 8
    patient_info_size: 3
  ibe:
    embed_dim: 256
    num_heads: 8
    ff_hidden_size: 1024
    num_layers: 3
    text_embed_dim: 768
    patient_info_size: 3

inference_setting:
  save_sample_path: test_samples
  gen_batch: 10
  hr: 60
  age: 60
  sex: F
  text: "sinus bradycardia|premature ventricular complex|lead unsuitable for analysis: V6."
  noise_predictor_path: checkpoints/DiT_ATTN_1/DiT_ATTN_best.pth
  inference_timestep: 1000