meta:
  exp_description: DiT ECGTwin
  exp_type: DiT_ECGTwin # name of saving folder 
  device: cuda:2
  model_type: DiT_ECGTwin
  vae_latent: True # Whether to use VAE
  mix: False # True for '_adaLN' model

dependencies:
  dataset_path: data/paired_Mimic_vae_multi_nomic.pt
  checkpoints_dir: checkpoints
  vae_path: checkpoints/vae_model.pth
  ibe_path: checkpoints/ibe_model.pth

hyper_para:
  epochs: 30
  lr: 1.0e-4
  batch_size: 512
  ddpm:
    num_train_steps: 1000
    beta_start: 0.00085 
    beta_end: 0.0120
  DiT:
    hidden_size: 256
    depth: 7
    num_heads: 8
    patient_info_size: 3
  ibe:
    embed_dim: 256
    num_heads: 8
    ff_hidden_size: 1024
    num_layers: 3
    text_embed_dim: 768
    patient_info_size: 3
  
# Used for inference
inference_setting:
  save_sample_path: generation_result
  gen_batch: 50 # Number of ECG generated
  hr: 70
  age: 70
  sex: F # Binary of 'F' or 'M'
  text: "sinus rhythm|normal ecg."
  noise_predictor_path: checkpoints/ECGTwin_DiT.pth
  inference_timestep: 1000