meta:
  exp_description: Unet ECGTwin
  exp_type: Unet_ECGTwin 
  device: cuda:6
  model_type: Unet_ECGTwin
  vae_latent: True
  mix: False

dependencies:
  dataset_path: data/paired_Mimic_vae_multi_nomic.pt
  checkpoints_dir: checkpoints
  vae_path: checkpoints/vae_model.pth
  ibe_path: checkpoints/ibe_model.pth

hyper_para:
  epochs: 30
  lr: 5.0e-4
  batch_size: 1024
  ddpm:
    num_train_steps: 1000
    beta_start: 0.00085 
    beta_end: 0.0120
  unet:
    kernel_size: 7
    num_level: 6
    n_heads: 8
    patient_info_size: 3
  ibe:
    embed_dim: 256
    num_heads: 8
    ff_hidden_size: 1024
    num_layers: 3
    text_embed_dim: 768
    patient_info_size: 3

inference_setting:
  save_sample_path: generation_result
  gen_batch: 10
  hr: 80
  age: 60
  sex: F
  text: "sinus rhythm|normal ecg."
  noise_predictor_path: checkpoints/ECGTwin_Unet.pth
  inference_timestep: 1000